### ISSUE TITLE
Ensure framerate consistent throughout all chain

### ISSUE THREAD

**Issue by xfxf** [xfxf/av-foss-stack#44]
We should be doing ~25fps everywhere, from the Opsis, to vocto ingests, to vocto, to saving, to encoding (veyepar melt options).  Suspect we're doing 25<>30 conversion in a few places currently.

**Comment by enjoy-digital** [comment]
For the opsis, you should be able to use the "encoder fps" command. But tests need to be done to be sure we are always able to provide 25fps in 720p. (it's possible it's not the case for frames that are difficult to encode and use more USB bandwidth)

**Comment by mithro** [comment]
All the Opsis are set to 25fps, the EDID is set to 720p{50,60}.

**Comment by xfxf** [comment]
This very much may be a non-issue already, I just want to verify.
