### ISSUE TITLE
Get networking up + running, including NAT

### ISSUE THREAD

**Issue by xfxf** [xfxf/av-foss-stack#50]

**Comment by CarlFK** [comment]
this is that

eth_uplink_mac_address: 60:a4:4c:b0:89:49

https://github.com/xfxf/av-foss-stack/blob/master/inventory/host_vars/gw1.yml#L2

more info
https://anonscm.debian.org/git/debconf-video/ansible.git/tree/roles/dhcp-server/defaults/main.yml

**Comment by xfxf** [comment]
@CarlFK we're not using your ansible stuff for this, thx anyway!

**Comment by micolous** [comment]
Network is happy, at least inside Room 102. Connection to ISP is good. Not sure about interconnect to other rooms -- we'll find out about that tomorrow once we can get in there.

The machines were already configured with the correct IPs and subnets so I'm not going to change that.
