### ISSUE TITLE
Things for next time

### ISSUE THREAD

**Issue by oheydrew** [xfxf/av-foss-stack#54]
- The Big One - No splitting the plenary room!
- Common power from stage - 20m power cables to go from lectern to rear of room for clean audio (Solves ground buzzes)
- RF Mic interference again - thorough run-down of RF systems, request for recievers to be placed in rooms in lieu of "installed" RF Systems (might have to fight for this, venues might want to charge extra, which I think isn't fair)
- Small audio mixers @ rear of room for manual control of mics - despite being told we could control them from AMX panels, we couldn't actually do this due to levels resetting and not having the full access password. Workaround is to have small mixers in room.
- Gobo is to be SOURCE 4 PROFILE/ZOOM (Not Source 4 Junior) and (learning, learning, always learning) the "Beam angle" is dependent on the room size. What we'd want is a 10 degree angle, we only had 20's on site @ mcec. #notesfornexttime

**Comment by micolous** [comment]
Note that next year we'll be in a different venue, so we get to have the fun all over again ;)
