### ISSUE TITLE
Set both of Carl's cameras to 50hz mode.

### ISSUE THREAD

**Issue by xfxf** [xfxf/av-foss-stack#59]
Carl's cameras come from the US.
By default they will do 60hz/60fps (NTSC).  This looks super wierd under fluro lights, we will get flickering.
Make sure they can all be sent to 50fps/50hz/PAL mode.  The JVC I know can be (I have the same camera), not sure about the panasonic.

If the panasonic can't we likely need to downgrade it to a smaller room (not one of the C rooms).

**Comment by keeperofdakeys** [comment]
Both cameras lack PAL output, so set to 24p. Will test flicking of
