### ISSUE TITLE
Learn how to build HDMI2USB firmware/gateware

### ISSUE THREAD

**Issue by xfxf** [xfxf/av-foss-stack#69]
(This was a ticket to show a LCA slide on the HDMI2USB - this isn't easily possible, so this is just a learning ticket now)

Follow the HDMI2USB build firmware/gateware instructions / ask Carl or Ryan or Tim for help / and make sure you can build it, flash it onto a HDMI2USB, ensure that's all OK.

(Ensure you're working off the approved version/commit of the firmware we're using elsewhere though!)

Look into how to replace or add one of the patterns with the LCA logo.  Build a new firmware/gateware.  If OK, flash to all other laptops.

**Comment by mithro** [comment]
@xfxf Unless you know something I don't - I can't see this happening?
